### PR TITLE
Pool2D parallel shape inference

### PR DESCRIPTION
**Pull request by Marsella8**
**Description of changes:**
Added Pool2D parallel shape inference

**Related Issues:**

Linked Issues:
- Issue #

Issues closed by this PR:
- Closes #

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
Can you add tests? You can find an example in https://github.com/lockshaw/FlexFlow/blob/88709f056892bdd90ce3a6a6c5060d0b91966df6/lib/op-attrs/test/src/test_batch_matmul.cc

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-:-Nyur5Xp-Zlw0vmN_CAy:b-bhsact)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marsella8)

**Review by Marsella8 — COMMENTED** [review]
test has been added

> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-:-NzCdJs813FsSqt07d69:brbpcaj)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @lockshaw)

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9)* status: all files reviewed, 1 unresolved discussion (waiting on @Marsella8)

___
*[`lib/op-attrs/test/src/test_pool_2d.cc` line 63 at r2](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-NzEjjgPChirwYKFgC36:-NzEjjgQ3Ag8-DgvIY-W:borecbg) ([raw file](https://github.com/lockshaw/FlexFlow/blob/e7746c1a384e7f9565925e6f711293c5e0722295/lib/op-attrs/test/src/test_pool_2d.cc#L63)):*
> ```cpp
>     CHECK(result == correct_output_shape);
>   }
> }
> ```

Tests for parallel shape inference (i.e., `get_output_shape(Pool2DAttrs, ParallelTensorShape)`) are also needed--see https://github.com/lockshaw/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/test/src/test_attention.cc for example

**Review by lockshaw — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9)* status: all files reviewed, 1 unresolved discussion (waiting on @Marsella8)

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/op-attrs/test/src/test_pool_2d.cc` line 63 at r2](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-NzEjjgPChirwYKFgC36:-NzG_BLK0JA--MUPkUSd:ba5xh0k) ([raw file](https://github.com/lockshaw/FlexFlow/blob/e7746c1a384e7f9565925e6f711293c5e0722295/lib/op-attrs/test/src/test_pool_2d.cc#L63)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Tests for parallel shape inference (i.e., `get_output_shape(Pool2DAttrs, ParallelTensorShape)`) are also needed--see https://github.com/lockshaw/FlexFlow/blob/1a6d1f8d9de10f1d9159686c61b13e07b71671b6/lib/op-attrs/test/src/test_attention.cc for example
</blockquote></details>

added tests for `get_output_shape(Pool2DAttrs, ParallelTensorShape)`. I'm still not entirely confident in how the shapes change when there is parallelization involved, so let me know if you see any glaring issues. I can briefly work on it later tonight if some additional changes are needed.

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9)* status: all files reviewed, 1 unresolved discussion (waiting on @Marsella8)

___
*[`lib/op-attrs/test/src/test_pool_2d.cc` line 63 at r2](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-NzEjjgPChirwYKFgC36:-NzKkAakCgEM-I3Aogth:b4vouxo) ([raw file](https://github.com/lockshaw/FlexFlow/blob/e7746c1a384e7f9565925e6f711293c5e0722295/lib/op-attrs/test/src/test_pool_2d.cc#L63)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

added tests for `get_output_shape(Pool2DAttrs, ParallelTensorShape)`. I'm still not entirely confident in how the shapes change when there is parallelization involved, so let me know if you see any glaring issues. I can briefly work on it later tonight if some additional changes are needed.
</blockquote></details>

Ideally have tests checking each of the individual parallelization schemes, as in https://github.com/lockshaw/FlexFlow/blob/cb2c862b77b9707335868a12c90ca6c18fd67863/lib/op-attrs/test/src/test_embedding.cc#L76-L130, as it makes it clearer what is actually being tested

**Review by Marsella8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lockshaw/FlexFlow/9)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @lockshaw)

___
*[`lib/op-attrs/test/src/test_pool_2d.cc` line 63 at r2](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-NzEjjgPChirwYKFgC36:-NzihkseEUxaDQveOhxi:b-7e65ha) ([raw file](https://github.com/lockshaw/FlexFlow/blob/e7746c1a384e7f9565925e6f711293c5e0722295/lib/op-attrs/test/src/test_pool_2d.cc#L63)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Ideally have tests checking each of the individual parallelization schemes, as in https://github.com/lockshaw/FlexFlow/blob/cb2c862b77b9707335868a12c90ca6c18fd67863/lib/op-attrs/test/src/test_embedding.cc#L76-L130, as it makes it clearer what is actually being tested
</blockquote></details>

I'm still unsure on how to model the kernel tensor (and how to infer the shape). Is it only (width, height) or do I also need to include the input channel size as a dimension?

**Comment by lockshaw** [comment]
*[`lib/op-attrs/test/src/test_pool_2d.cc` line 63 at r2](https://reviewable.io/reviews/lockshaw/FlexFlow/9#-NzEjjgPChirwYKFgC36:-NzocwKeDhGt9UGzMwzv:bssfpka) ([raw file](https://github.com/lockshaw/FlexFlow/blob/e7746c1a384e7f9565925e6f711293c5e0722295/lib/op-attrs/test/src/test_pool_2d.cc#L63)):*
<details><summary><i>Previously, Marsella8 wrote…</i></summary><blockquote>

I'm still unsure on how to model the kernel tensor (and how to infer the shape). Is it only (width, height) or do I also need to include the input channel size as a dimension?
</blockquote></details>

I don't think you have a kernel tensor here, as `Pool2D` doesn't have any weights, so all you'd need to check is `get_output_shape`. Other operators, e.g., Conv2D, have one or more weights, so they have additional functions to check (for Conv2D, `get_kernel_shape`, `get_bias_shape`, `get_output_shape`)

**Comment by lockshaw** [comment]
Superseded by https://github.com/flexflow/FlexFlow/pull/1495

**Pull request closed without merging**
